name: comp3710
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip

  - pip:
      - torch --index-url https://download.pytorch.org/whl/cu118
      - torchvision --index-url https://download.pytorch.org/whl/cu118
      - torchaudio --index-url https://download.pytorch.org/whl/cu118
      - matplotlib
      - nibabel
      - tqdm
